-- =====================================================================
-- Project Zomboid Build 42 unstable - SandboxVars
-- Balanced survival, optimizado para 20 jugadores + modlist pesado.
-- =====================================================================

SandboxVars = {
    VERSION = 5,

    -- === Zombies (perf + balance) ===
    Zombies = 3,
    Distribution = 1,
    DayLength = 3,
    StartYear = 1,
    StartMonth = 7,
    StartDay = 9,
    StartTime = 2,
    WaterShut = 2,
    ElecShut = 2,
    WaterShutModifier = 30,
    ElecShutModifier = 30,
    FoodLoot = 2,
    WeaponLoot = 2,
    OtherLoot = 2,
    Temperature = 3,
    Rain = 3,
    ErosionSpeed = 3,
    ErosionDays = 0,
    XpMultiplier = 1.0,
    XpMultiplierAffectsPassive = false,
    StatsDecrease = 3,
    NatureAbundance = 3,
    Alarm = 2,
    LockedHouses = 6,
    StarterKit = false,
    Nutrition = true,
    FoodRotSpeed = 3,
    FridgeFactor = 3,
    LootRespawn = 4,
    SeenHoursPreventLootRespawn = 24,
    HoursForLootRespawn = 336,
    MaxItemsForLootRespawn = 4,
    ConstructionPreventsLootRespawn = true,
    TimeSinceApo = 1,
    PlantResilience = 3,
    PlantAbundance = 3,
    EndRegen = 3,
    Helicopter = 2,
    MetaEvent = 2,
    SleepingEvent = 1,
    GeneratorSpawning = 3,
    GeneratorFuelConsumption = 1.0,
    SurvivorHouseChance = 3,
    VehicleStoryChance = 3,
    ZoneStoryChance = 3,
    AnnotatedMapChance = 4,
    CharacterFreePoints = 5,
    ConstructionBonusPoints = 3,
    NightDarkness = 3,
    InjurySeverity = 2,
    BoneFracture = true,
    HoursForCorpseRemoval = 168,
    DecayingCorpseHealthImpact = 3,
    BloodLevel = 3,
    ClothingDegradation = 3,
    FireSpread = true,
    DaysForRottenFoodRemoval = -1,
    AllowExteriorGenerator = true,
    MaxFogIntensity = 1,
    MaxRainFxIntensity = 1,
    EnableSnowOnGround = true,
    MultiHitZombies = true,
    RearVulnerability = 3,
    AttackBlockMovements = true,
    AllClothesUnlocked = false,
    CarSpawnRate = 3,
    ChanceHasGraphicIssues = 1,
    DamageToPlayerFromHitByACar = 2,
    TrafficJam = true,
    CarAlarm = 2,
    PlayerDamageFromCrash = true,
    SirenShutoffHours = 0.0,
    CarGeneralCondition = 3,
    CarDamageOnImpact = 3,
    DamageToVehiclesFromZombies = 1,
    CarEnginePerformance = 2,
    LowGasolineConsumption = 1,
    GasolineExpiration = 0,
    EngineLoudness = 1.0,
    VehicleEasyUse = false,
    AdvancedMechanics = true,
    Brakes = 3,
    KeepHungerThirstWhenSleeping = false,
    EnableTaintedWaterText = true,
    HotwireBaseChance = 1,
    HotwireSkillModifier = 2,
    AnimalDistribution = 2,
    AnimalsTrackInWorld = 0,
    HerdAnimalsHerdSize = 5,
    WildAnimalsBreed = false,

    -- === Build 42 nuevo ===
    BasementsEnabled = true,
    CraftingOverhaul = true,
    FluidContainersEnabled = true,
    GeneticDiseases = false,
    HempCraftingEnabled = false,

    ZombieLore = {
        Speed = 2,
        Strength = 2,
        Toughness = 2,
        Transmission = 1,
        Mortality = 5,
        Reanimate = 3,
        Cognition = 3,
        CrawlUnderVehicle = 2,
        Memory = 3,
        Sight = 1,
        Hearing = 3,
        ThumpNoChasing = true,
        ThumpOnConstruction = true,
        ActiveOnly = 1,
        TriggerHouseAlarm = true,
        ZombiesDragDown = true,
        ZombiesFenceLunge = true,
        DisableFakeDead = 1,
    },

    ZombieConfig = {
        PopulationMultiplier = 1.0,
        PopulationStartMultiplier = 1.0,
        PopulationPeakMultiplier = 1.3,
        PopulationPeakDay = 28,
        RespawnHours = 72.0,
        RespawnUnseenHours = 24.0,
        RespawnMultiplier = 0.05,
        RedistributeHours = 12.0,
        FollowSoundDistance = 100,
        RallyGroupSize = 0,
        RallyTravelDistance = 20,
        RallyGroupSeparation = 15,
        RallyGroupRadius = 3,
        SimulatePhysics = false,
        SimulateRolls = 0,
        RallyDeadZombiesGroupSize = 0,
    },

    SafehouseAllowTrepass = true,
    SafehouseAllowFire = true,
    SafehouseAllowLoot = true,
    SafehouseAllowRespawn = true,
    SafehouseDaySurvivedToClaim = 2,
    SafeHouseRemovalTime = 144,
    SafehouseAllowNonResidential = true,
    AllowDestructionBySledgehammer = true,
    SledgehammerOnlyInSafehouse = false,
    KickOffPlayersFromSafehousesIfTheyAreNotMembers = false,
    PlayerSafehouse = true,
    AdminSafehouse = false,
    SafehouseAllowTrepass = true,
    SafehouseAllowFire = true,
    SafehouseAllowLoot = true,
    FireSpread = true,
    DaysForRottenFoodRemoval = -1,
    AllowExteriorGenerator = true,
    MaxFogIntensity = 1,
    MaxRainFxIntensity = 1,
    EnableSnowOnGround = true,
    MultiHitZombies = true,
    RearVulnerability = 3,
    AttackBlockMovements = true,
    AllClothesUnlocked = false,

    Map = {
        AllowMiniMap = true,
        AllowWorldMap = true,
        MapAllKnown = true,
    },

    -- Deshabilitar prying de CommonSense: usa STA_PryOpen que tiene mejor manejo MP
    CommonSense = {
        PryingMechanic = false,
    },
}
